name: CBS
main: gold.eggs.commandblockspy.MainPlugin
version: v1.0.0-SNAPSHOT-1
api-version: 1.21
commands:
  cbspy:
    aliases: [cbs]
    description: Command Block Spy Plugin
    usage: /cbspy
    permission: cbspy.use
permissions:
  cbspy.use:
    default: true
  cbspy.reload:
    default: true
  cbspy.query:
    default: true