name: CBSpy
main: gold.eggs.commandblockspy.MainPlugin
version: v1.0.0-SNAPSHOT-2
api-version: 1.21
commands:
  cbspy:
    description: Command Block Spy Plugin
    usage: /cbspy
    permission: cbspy.use
permissions:
  cbspy.use:
    default: op
  cbspy.reload:
    default: op
  cbspy.query:
    default: op
  cbspy.intercept:
    default: op